# Digital Ocean
# Kubernetes cluster creation definitions, generated by ./configure.
# It's OK to modify this file as necessary to customize your deployment,
# but note it may be overwritten if ./configure is run again.

# Cloud hosting provider
PROVIDER=do				# Cloud hosting provider

# Kubernetes cluster definitions
CLUSTER_NAME=genesis			# Kubernetes cluster name
K8S_VERSION=1.16.2-do.1			# Kubernetes engine version
SIZE=s-4vcpu-8gb			# Node type to use for the k8s cluster
NODES=3					# Number of nodes in the k8s cluster
NODE_POOL_NAME=\$SIZE			# Name of the k8s node pool
REGION=sfo2				# DO region where to create the k8s cluster
CONTEXT=do-\$REGION-\$CLUSTER_NAME	# Name of the k8s context for the cluster
DASHBOARD_VERSION=v2.0.0-beta6		# The version of Kubernetes Dashboard to install

# JupyterHub version to install, and kubernetes namespace to install it into
JHUB_VERSION=0.9.0-alpha.1.090.1810aa5	# JupyterHub Helm chart version
JHUB_HELM_RELEASE=genesis-hub		# The name of the installed release
JHUB_K8S_NAMESPACE=genesis-hub		# The k8s namespace to install into

# JupyterHub image configuration
HUB_IMAGE=mjuric/hub:gallifrey.local-20191212144614		# custom JupyterHub image (e.g. foo/hub:v0.3)
JUPYTER_IMAGE=mjuric/jupyter:gallifrey.local-20191125235836	# custom Jupyter Notebook image (e.g., foo/jupyter-notebook:v0.43)

# Environment customization via script
AUTOEXEC_SCRIPT=			# File with commands to run every time the user logs in

# JupyterHub fully qualified domain name
HUB_FQDN=				# The domain name of the hub (REQUIRED)
PREFIX=\$HUB_FQDN			# Output directory for the generated configuration

# Let's Encrypt SSL cerfiticates information
LETSENCRYPT_EMAIL=			# E-mail for Let's Encrypt (REQUIRED)

# GitHub Authentication
GITHUB_OAUTH_CLIENT_ID=			# GitHub OAuth App Client ID
GITHUB_OAUTH_SECRET=			# OAuth client secret
GITHUB_OAUTH_CREDS=			# The file with GitHub OAuth App Client ID (first line) and secret (second)
GITHUB_ORG=				# If set, allow only users from this org

# JupyterHub user settings
ADMIN_USER=				# User ID of the JupyterHub administraator
USER_DISK=1				# Amount of disk per user, in gigabytes
USER_CPU=0.5				# Number of CPU cores to allocate, per user
USER_MEMORY=1.0				# GB of RAM to allocate, per user
