# Digital Ocean
# Kubernetes cluster creation definitions, generated by ./configure.
# It's OK to modify this file as necessary to customize your deployment,
# but note it may be overwritten if ./configure is run again.

# Cloud hosting provider
PROVIDER=do				# Cloud hosting provider

# Kubernetes cluster definitions
CLUSTER_NAME=genesis			# Kubernetes cluster name
K8S_VERSION=1.15.5-do.1			# Kubernetes engine version
SIZE=s-4vcpu-8gb			# Node type to use for the k8s cluster
NODES=3					# Number of nodes in the k8s cluster
NODE_POOL_NAME=$(SIZE)			# Name of the k8s node pool
REGION=sfo2				# DO region where to create the k8s cluster
CONTEXT=do-$(REGION)-$(CLUSTER_NAME)	# Name of the k8s context for the cluster

# JupyterHub version to install, and kubernetes namespace to install it into
JHUB_VERSION=0.9.0-alpha.1.028.00bc15c	# JupyterHub Helm chart version
JHUB_HELM_RELEASE=genesis-jhub		# The name of the installed release
JHUB_K8S_NAMESPACE=genesis		# The k8s namespace to install into

# JupyterHub fully qualified domain name
HUB_FQDN=				# The domain name of the hub (REQUIRED)

# Let's Encrypt SSL cerfiticates information
LETSENCRYPT_EMAIL=			# E-mail for Let's Encrypt

# GitHub Authentication
GITHUB_OAUTH_CLIENT_ID=			# GitHub OAuth App Client ID
GITHUB_OAUTH_SECRET=			# OAuth client secret
