##vars ADMIN_USER USER_DISK USER_CPU
jupyterhub:
  hub:
    extraConfig:
      timeout: |
        c.Spawner.http_timeout = 600
  cull:
    enabled: true
    timeout: 3600
auth:			##if -n $ADMIN_USER
  admin:		##if -n $ADMIN_USER
    access: true	##if -n $ADMIN_USER
    users:		##if -n $ADMIN_USER
      - $ADMIN_USER	##if -n $ADMIN_USER
hub:
  image:
    name: mjuric/k8s-hub-dirac
    tag: 0.9.0-alpha.1.020.c70f016-mjuric1
  extraConfig:
    myConfig: |
       c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/images/logo.png'
singleuser:
  image:
    name: mjuric/genesis-notebook
    tag: 0.1
  memory:
    guarantee: ${USER_MEMORY}G
  cpu:
    guarantee: $USER_CPU
  storage:
    capacity: ${USER_DISK}Gi
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - |
            rm -rf genesis-client .ipython/genesis
            git clone https://github.com/dirac-institute/genesis-client
            ln -s ../genesis-client/genesis .ipython/genesis
            gitpuller https://github.com/dirac-institute/genesis-streaming-demo master genesis-streaming-demo
