jupyterhub:
  hub:
    extraConfig:
      timeout: |
        c.Spawner.http_timeout = 600
  cull:
    enabled: true
    timeout: 3600
hub:
  image:
    name: mjuric/k8s-hub-dirac
    tag: 0.9.0-alpha.1.020.c70f016-mjuric1
  extraConfig:
    myConfig: |
       c.JupyterHub.logo_file = '/usr/local/share/jupyter/hub/static/images/logo.png'
singleuser:
  image:
    name: mjuric/genesis-notebook
    tag: 0.1
  memory:
    guarantee: 4G
    limit: 8G
  cpu:
    guarantee: 3.1
    limit: 8
  storage:
    capacity: 1Gi
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "/bin/sh"
          - "-c"
          - |
            rm -rf genesis-client .ipython/genesis
            git clone https://github.com/dirac-institute/genesis-client
            ln -s ../genesis-client/genesis .ipython/genesis
            gitpuller https://github.com/dirac-institute/genesis-streaming-demo master genesis-streaming-demo

#        command: ["rm", "-rf", "genesis-client", ".ipython/genesis"]
#        command: ["git", "clone", "https://github.com/dirac-institute/genesis-client"]
#        command: ["ln", "-s", "../genesis-client/genesis", ".ipython/genesis"]
#        command: ["gitpuller", "https://github.com/dirac-institute/genesis-streaming-demo", "master", "genesis-streaming-demo"]
