#!/bin/bash
#
# Set up k8s web dashboard (check for new versions at https://github.com/kubernetes/dashboard/releases)
#

set -e

# Switch to deployment directory and load the config
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$(dirname $DIR)"
. config
. scripts/common.sh

# Install the dashboard, if needed
if [[ -z "$(kubectl get pods -n kubernetes-dashboard 2>/dev/null)" ]]; then
	kubectl delete ns kubernetes-dashboard 2>/dev/null || true

	kubectl apply -f dashboard/dashboard.yaml
	kubectl apply -f dashboard/create-dashboard-admin-user.yaml

	rm -f secrets/dashboard.token

	echo "Dashboard installed; the password token is in 'secrets/dashboard.token'"
	echo "Run 'kubectl proxy &', and visit http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login"
else
	echo "k8s dashboard GUI already installed. skipping."
fi

# Grab the access token for the GUI
if [[ ! -f secrets/dashboard.token ]]; then
  mkdir -p secrets

  kubectl -n kubernetes-dashboard describe secret \
    $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}') \
    | grep -E '^token:' | sed 's/^token: *//' > secrets/dashboard.token
fi

echo "You can find the login token in the 'secrets/dashboard.token' file."
