#!/bin/bash

set -e

# Switch to deployment directory and load the config
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$(dirname $DIR)"
. config
. scripts/common.sh

assert_defined JHUB_HELM_RELEASE JHUB_K8S_NAMESPACE JHUB_VERSION

# Enumerate all config files
VALUES=( $(ls values/*.yaml 2>/dev/null) )

# Enumerate all secrets
SECRETS=( $(ls secrets/*.yaml 2>/dev/null) )

# Run Helm
kubectl create namespace "$JHUB_K8S_NAMESPACE" >/dev/null 2>&1 || true
helm repo update
helm upgrade $JHUB_HELM_RELEASE \
     jupyterhub/jupyterhub  \
     --namespace "$JHUB_K8S_NAMESPACE" \
     --version="$JHUB_VERSION" \
     ${VALUES[@]/#/--values } \
     ${SECRETS[@]/#/--values } \
     --timeout=800 \
     "$@"
